--- ./Makefile.am~	2004-02-06 17:04:39.000000000 +0100
+++ ./Makefile.am	2005-09-13 02:20:23.000000000 +0200
@@ -2,7 +2,7 @@
 
 EXTRA_DIST = faad2.spec
 
-rpm:    Makefile
-       make dist
-       $(RPMBUILD) -ta $(PACKAGE)-$(VERSION).tar.gz
-       rm $(PACKAGE)-$(VERSION).tar.gz
+rpm: Makefile
+	make dist
+	$(RPMBUILD) -ta $(PACKAGE)-$(VERSION).tar.gz
+	rm $(PACKAGE)-$(VERSION).tar.gz
