diff -ruN chan_misdn-beta-0.0.3-rc6/Makefile chan_misdn-beta-0.0.3-rc6-new/Makefile
--- chan_misdn-beta-0.0.3-rc6/Makefile	2005-02-14 15:36:14.000000000 +0100
+++ chan_misdn-beta-0.0.3-rc6-new/Makefile	2005-06-17 11:05:18.000000000 +0200
@@ -23,15 +23,15 @@
 #
 # The Includes are Set appropriatly
 #
-ASTERISKINC=$(ASTERISKSRC)/include
+ASTERISKINC=/usr/include
 
 
 #
 # mISDNuser PATHS
 #
-MISDNUSER=/usr/src/mISDNuser
-MISDNUSERINC=$(MISDNUSER)/include
-MISDNUSERLIB=$(MISDNUSER)/lib
+MISDNUSER=/usr
+MISDNUSERINC=$(MISDNUSER)/include/mISDN
+MISDNUSERLIB=$(MISDNUSER)/lib/mISDN
 
 #
 # mISDNuser Version
@@ -49,7 +49,7 @@
 CFLAGS+=-DASTERISK_STABLE
 
 
-LINUXROOT=/usr/src/linux-2.6
+LINUXROOT=/usr/src/linux
 
 #
 # Kernel 2.4 ? 
@@ -66,14 +66,14 @@
 
 all: chan_misdn.so
 
-CFLAGS+=-fPIC -I$(ASTERISKINC) -DAST_CONFIG_DIR=\"$(AST_CONFIG_DIR)\" -I$(MISDNUSERINC) -I$(LINUXINC) -I$(MISDNUSER)/i4lnet/ -Wall
-ADDOBJS+=$(MISDNUSER)/i4lnet/libisdnnet.a $(MISDNUSER)/lib/libmISDN.a
+CFLAGS+=-fPIC -I$(ASTERISKINC) -DAST_CONFIG_DIR=\"$(AST_CONFIG_DIR)\" -I$(MISDNUSERINC) -I$(LINUXINC) -I$(MISDNUSERINC)/i4lnet/ -Wall
+ADDOBJS+=$(MISDNUSERLIB)/i4lnet/libisdnnet.a $(MISDNUSERLIB)/libmISDN.a
 
 chan_misdn.so: chan_misdn.o te_lib.o crypt.o $(ADDOBJS)
 	$(CC) -shared -Xlinker -x -o $@ te_lib.o crypt.o chan_misdn.o $(ADDOBJS) 
 
 testphone:  testphone.c
-	$(CC) -I$(MISDNUSERINC) -I$(MISDNUSER)/i4lnet/ -I$(LINUXINC)  testphone.c $(MISDNUSERLIB)/libmISDN.a -o testphone
+	$(CC) -I$(MISDNUSERINC) -I$(MISDNUSERINC)/i4lnet/ -I$(LINUXINC)  testphone.c $(MISDNUSERLIB)/libmISDN.a -o testphone
 
 install: chan_misdn.so
 	install -m 644 chan_misdn.so $(INSTALL_MODPATH)/
@@ -95,16 +95,16 @@
 
 
 te_lib.o: te_lib.c te_lib.h isdn_msg.c isdn_msg_parser.c
-	$(CC) -I$(MISDNUSERINC) -I$(MISDNUSER)/i4lnet/ -I$(LINUXINC) $(CFLAGS) -ggdb -c te_lib.c
+	$(CC) -I$(MISDNUSERINC) -I$(MISDNUSERINC)/i4lnet/ -I$(LINUXINC) $(CFLAGS) -ggdb -c te_lib.c
 
 crypt.o: crypt.c crypt.h 
 	$(CC) $(CFLAGS) -ggdb -c crypt.c
 
 te_test.o: te_test.c
-	$(CC) -I$(MISDNUSERINC) -I$(MISDNUSER)/i4lnet/ -I$(LINUXINC) $(CFLAGS)-ggdb -c te_test.c
+	$(CC) -I$(MISDNUSERINC) -I$(MISDNUSERINC)/i4lnet/ -I$(LINUXINC) $(CFLAGS)-ggdb -c te_test.c
 
 te_test: te_lib.o te_test.o
-	$(CC) -I$(MISDNUSERINC) -I$(MISDNUSER)/i4lnet/ -I$(LINUXINC) $(CFLAGS) te_lib.o te_test.o $(MISDNUSERLIB)/libmISDN.a $(MISDNUSER)/i4lnet/libisdnnet.a -lpthread -ggdb -o te_test
+	$(CC) -I$(MISDNUSERINC) -I$(MISDNUSERINC)/i4lnet/ -I$(LINUXINC) $(CFLAGS) te_lib.o te_test.o $(MISDNUSERLIB)/libmISDN.a $(MISDNUSERLIB)/i4lnet/libisdnnet.a -lpthread -ggdb -o te_test
 #$(MISDNUSERLIB)/libmISDN.a 
 
 clean: 
